import type { Metadata } from "next";
import Image from "next/image";
import { StPeterProvider } from "st-peter-ui";
import "./globals.css";
import Footer from "@/components/ui/footer";
import ServiceWorkerRegister from "@/components/service-worker";
import { DemoAuthProvider } from "@/components/ui/demo-auth";
import { AppLayoutWrapper } from "@/components/layout/app-layout-wrapper";
import NotifyInstall from "@/components/ui/notify-install";
export const metadata: Metadata = {
  title: "St. Peter eStore",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <head>
        <title>St. Peter eStore</title>
        <meta
          name="viewport"
          content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no"
        />
        <link rel="apple-touch-icon" href="/icon-192.png" />
        <meta name="apple-mobile-web-app-capable" content="yes" />
        <meta
          name="apple-mobile-web-app-status-bar-style"
          content="black-translucent"
        />
        <meta name="apple-mobile-web-app-title" content="eStore" />
      </head>
      <body>
        <ServiceWorkerRegister />
        <StPeterProvider theme="green" font="Open Sans">
          <DemoAuthProvider>
            <NotifyInstall>
              {/* overflowX on an inner div so Portal-rendered fixed elements
                  (Dialog backdrop/positioner) are not trapped inside it */}
              <div style={{ overflowX: "hidden" }}>
                <AppLayoutWrapper>
                  {children}
                  <Footer />
                </AppLayoutWrapper>
              </div>
            </NotifyInstall>
          </DemoAuthProvider>
        </StPeterProvider>
      </body>
    </html>
  );
}
